### ISSUE TITLE
URL parsing

### ISSUE THREAD

**Issue by Sorunome** [RicinApp/Ricin#80] opened 2016-03-31 17:40 UTC
when you parse a link like https://ricin.im/ it will first parse the italics and then url or something so that it'll actually open `https://<i>ricin.im</i>` in the browser
##

**Comment by SkyzohKey** [comment] 2016-04-01 01:19
Hi, thanks for the bug report! This is a known issue caused by the way Ricin handles Markdown (shitty regexes). I'll need to write a proper Markdown parser in order to have things working perfectly.

**Comment by SkyzohKey** [comment] 2016-04-14 08:33
@Sorunome The issue have been fixed with 0.0.5 (new settings pr) I guess, feel free to reopen if you think the bug is still here. ;)

**Comment by Sorunome** [comment] 2016-04-15 22:17
bug is still there, happens if you have http:// &lt;url&gt; /

So if there is a trailing slash after the URL but no additional path

**Comment by SkyzohKey** [comment] 2016-04-16 00:16
Ah! Shiiiiiiiiiiiiit. I reopen then x)

**Comment by SkyzohKey** [comment] 2016-05-03 09:46
That's fixed. :)

**Closed as completed by SkyzohKey** 2016-05-03 09:46 UTC
Labels: bug, chat_view, p-required
