### ISSUE TITLE
crashing on file transfer

### ISSUE THREAD

**Issue by Sorunome** [RicinApp/Ricin#91] opened 2016-04-03 19:05 UTC
When recieving the second file in a row from somebody without restarting ricin it crashes (busy wait, forces me to `killall -9 ricin` ).
It happens always, might have to do with the filename of the files being the same (utox-inline)
##

**Comment by SkyzohKey** [comment] 2016-04-06 01:20
This is a known issue. Also a duplicate of #35. I'll close the old one.

**Comment by SkyzohKey** [comment] 2016-04-09 00:42
Duplicate of #52, closing.

**Comment by Sorunome** [comment] 2016-04-14 18:16
It's not really a duplicate as the files in question don't contain a space in their name....

**Closed as completed** 2016-05-03 04:17 UTC
Labels: bug, chat_view
